package com.freva.projecteuler.lvl0;

import com.freva.projecteuler.Problem;

/**
 * Project Euler problem #002:
 * Answer: 4613732, Time: 0ms
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */

public class Problem002 implements Problem {
    public Number solve() {
        int sumOfEvenFibonacciNumbers = 0;

        for (int i0 = 1, i1 = 1; i1 < 4_000_000; ) {
            int temp = i1;
            i1 += i0;
            i0 = temp;

            if (i0 % 2 == 0) {
                sumOfEvenFibonacciNumbers += i0;
            }
        }

        return sumOfEvenFibonacciNumbers;
    }
}
