package com.freva.projecteuler.lvl1;

import com.freva.projecteuler.Problem;

/**
 * Project Euler problem #045:
 * Answer: 1533776805, Time: 1ms
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal   Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

public class Problem045 implements Problem {
    public Number solve() {
        for (int n = 145; ; n++) {
            // All triangle numbers are also hexagonal numbers, thus we only need to find a pentagonal number that is
            // also a hexagonal number
            final long hexagonal = n * (2 * n - 1);
            final double k = (1 + Math.sqrt(1 + 24 * hexagonal)) / 6;

            if (k == (int) k) {
                return hexagonal;
            }
        }
    }
}
